window.i18n = {
    en: {
        site: { title: 'DesktopRenamer — Rename Your Experiences' },
        hero: { heading: 'DesktopRenamer', tagline: 'Rename Your Experiences.' },
        quicknav: { page: 'Page', links: 'Links', more: 'macOSers', workflowSuite: 'Workflow', mediaSuite: 'Media', overview: 'Overview', demo: 'Demo', features: 'Features', install: 'Install', docs: 'Docs', github: 'GitHub', releases: 'Releases', raycast: 'Raycast', portfolio: 'Portfolio', blog: 'Blog', optclicker: 'OptClicker', spaceswitcher: 'SpaceSwitcher' },
        overview: { label: 'Overview', headingHtml: 'Take back control of your <span class="text-editorial gradient-text">macOS spaces.</span>', body: 'DesktopRenamer is a macOS menubar app that lets you give custom names to your desktop spaces — those virtual desktops you create in Mission Control.' },
        demo: { label: 'Demo', watch: 'Watch Full Video', close: 'Close video' },
        features: { label: 'Features', headingHtml: 'Everything you need to <span class="text-editorial gradient-text">own</span> your workflow.', slide1num: '01 / Rename', slide1title: 'Rename at <span class="text-editorial gradient-text">Menu Bar</span>', slide1body: 'Give your desktop spaces custom names directly from the menu bar. Click, type, done.', slide2num: '02 / Labels', slide2title: 'Crystal Clear <span class="text-editorial gradient-text">Labels</span>', slide2body: 'Aesthetic name labels in Mission Control. A discreet active label confirms your space after switching.', slide3num: '03 / Navigate', slide3title: 'Switch <span class="text-editorial gradient-text">&</span> Move', slide3body: 'Click a space to jump to it. Hold Option to teleport the active window — no dragging.', slide4num: '04 / Speed', slide4title: 'Faster <span class="text-editorial gradient-text">Switching</span>', slide4body: 'Bypass macOS animation lag with trackpad overrides or keyboard hotkeys for instant switching.', slide5num: '05 / Lock', slide5title: '<span class="text-editorial gradient-text">Lock</span> Space', slide5body: 'When a space switch is triggered by opening the window of an app, move that window back to the original space. This way, you are always focused in the locked space.', slide5watch: 'Watch Demo', slide6num: '06 / Raycast', slide6title: 'Raycast <span class="text-editorial gradient-text">Extension</span>', slide6body: 'Manage and switch spaces from Raycast, your favorite launcher. Batch-move windows across spaces with a single command.', slide6btn: 'Install Raycast Extension', slide6watch: 'Watch Demo' },
        moreFeatures: { apiLabel: 'API & AppleScript', apiBody: 'Full AppleScript and API for automating space management from your own scripts and tools.', docs: 'Read the developer documentation', widgetLabel: 'Widget', widgetBody: 'See your current space and tap to switch — directly from the Notification Center or Desktop widget.' },
        install: { label: 'Install', headingHtml: 'Get started in <span class="text-editorial" style="color: var(--gold-light); font-style: italic;">seconds.</span>', body: 'macOS 13.0+. No SIP disable. Drag to Applications, done.', download: 'Download', or: 'or', copy: 'Copy', disclaimer: 'Not signed with a paid Apple Developer account — go to <strong>System Settings → Privacy & Security</strong> if macOS blocks the app. Permissions are guided on first launch.' },
        companions: { label: 'Companions', workflowSuite: 'Workflow', mediaSuite: 'Media', headingHtml: 'Works great with your <span class="text-editorial gradient-text">toolkit</span>.', spaceswitcherTitle: 'SpaceSwitcher', spaceswitcherBody: 'Control which app and set of dock items to display in each space. Pair with DesktopRenamer for complete workspace mastery.', optclickerTitle: 'OptClicker', optclickerBody: 'Right-click with the Option key. A simple utility that complements your DesktopRenamer workflow.', vtplayerTitle: 'VTPlayer', vtplayerBody: 'Enhance video with sharper detail and smoother motion on macOS and iPhone.', learnMore: 'Learn More' },
        footer: { copyright: '© 2026 - Michael Qiu.', brand: 'DesktopRenamer.' },
        sidebar: { home: 'Home', overview: 'Overview', demo: 'Demo', features: 'Features', install: 'Install', companions: 'Companions', github: 'GitHub' },
        sectionLabels: { home: 'Home', overview: 'Overview', demo: 'Demo', features: 'Features', 'more-features': 'Features', install: 'Install', companions: 'Companions' }
    },
    zh: {
        site: { title: 'DesktopRenamer — 重命名你的体验' },
        hero: { heading: 'DesktopRenamer', tagline: '重命名你的体验。' },
        quicknav: { page: '页面', links: '链接', more: 'macOSers', workflowSuite: '工作流', mediaSuite: '媒体', overview: '概览', demo: '演示', features: '功能', install: '安装', docs: '文档', github: 'GitHub', releases: '发布', raycast: 'Raycast', portfolio: '主页', blog: '博客', optclicker: 'OptClicker', spaceswitcher: 'SpaceSwitcher' },
        overview: { label: '概览', headingHtml: '重新掌控你的<span class="text-editorial gradient-text"> macOS 桌面。</span>', body: 'DesktopRenamer 是一款菜单栏应用，让你自定义 macOS 桌面名称。' },
        demo: { label: '演示', watch: '观看完整视频', close: '关闭视频' },  
        features: { label: '功能', headingHtml: '<span class="text-editorial gradient-text">掌控</span>工作流所需的一切。', slide1num: '01 / 重命名', slide1title: '<span class="text-editorial gradient-text">菜单栏</span>重命名', slide1body: '直接从菜单栏为命名桌面。点击、输入、完成。', slide2num: '02 / 标签', slide2title: '清晰<span class="text-editorial gradient-text">标签</span>', slide2body: '在调度中心查看预览标签。在桌面查看活跃标签。', slide3num: '03 / 导航', slide3title: '切换<span class="text-editorial gradient-text">与</span>移动', slide3body: '点击菜单即可跳转桌面。按住 Option 键即可移动当前窗口——无需拖拽。', slide4num: '04 / 速度', slide4title: '疾速<span class="text-editorial gradient-text">切换</span>', slide4body: '通过触控板覆盖或键盘快捷键绕过 macOS 动画延迟，实现即时切换。', slide5num: '05 / 锁定', slide5title: '<span class="text-editorial gradient-text">锁定</span>桌面', slide5body: '当某应用通过打开窗口触发桌面切换时，自动将该窗口移回原桌面。这样，你将始终保持在锁定桌面中专注工作。', slide5watch: '观看演示', slide6num: '06 / Raycast', slide6title: '<span class="text-editorial gradient-text">Raycast</span> 扩展', slide6body: '用你最爱的启动器 Raycast 管理和切换桌面。一键批量移动窗口到不同桌面。', slide6btn: '安装 Raycast 扩展', slide6watch: '观看演示' },
        moreFeatures: { apiLabel: 'API 与 AppleScript', apiBody: '完整的 AppleScript 和 API，让你通过自己的脚本和工具自动化桌面管理。', docs: '阅读开发者文档', widgetLabel: '小组件', widgetBody: '直接从通知中心或桌面的小组件切换桌面。' },
        install: { label: '安装', headingHtml: '即刻<span class="text-editorial" style="color: var(--gold-light);">开始。</span>', body: 'macOS 13.0+。无需禁用 SIP。拖入 Applications 文件夹，完成。', download: '下载', or: '或', copy: '复制', disclaimer: '未使用付费 Apple 开发者账号签名——如果 macOS 阻止该应用，请前往<strong>系统设置 → 隐私与安全性</strong>。首次启动时会引导完成权限设置。' },
        companions: { label: '配套', workflowSuite: '工作流', mediaSuite: '媒体', headingHtml: '完美契合你的<span class="text-editorial gradient-text">工作流</span>。', spaceswitcherTitle: 'SpaceSwitcher', spaceswitcherBody: '按桌面设置 App 规则和自定义程序坞。搭配 DesktopRenamer，切换桌面，工作区随之而动。', optclickerTitle: 'OptClicker', optclickerBody: '用 Option 键实现右键点击。配合 DesktopRenamer 可以单独控制每个桌面是否启用。', vtplayerTitle: 'VTPlayer', vtplayerBody: '在 Mac 和 iPhone 上提升视频画质，让细节更清晰、运动更流畅。', learnMore: '了解更多' },
        footer: { copyright: '© 2026 - Michael Qiu.', brand: 'DesktopRenamer.' },
        sidebar: { home: '首页', overview: '概览', demo: '演示', features: '功能', install: '安装', companions: '配套', github: 'GitHub' },
        sectionLabels: { home: '首页', overview: '概览', demo: '演示', features: '功能', 'more-features': '功能', install: '安装', companions: '配套' }
    }
};
